name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'todo_list_app'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'

    - name: Disable Flutter analytics
      run: flutter config --no-analytics

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Checking todo_list_app directory:"
        ls -la todo_list_app/

    - name: Change to project directory
      run: cd todo_list_app

    - name: Verify we are in correct directory
      run: |
        echo "Current directory: $(pwd)"
        echo "Checking for pubspec.yaml:"
        if [ -f "pubspec.yaml" ]; then
          echo "✅ pubspec.yaml found!"
        else
          echo "❌ pubspec.yaml not found!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi

    - name: Install dependencies
      run: |
        cd todo_list_app
        flutter pub get

    - name: Run tests
      run: |
        cd todo_list_app
        flutter test

    - name: Check formatting
      run: |
        cd todo_list_app
        flutter format --set-exit-if-changed .

    - name: Analyze code
      run: |
        cd todo_list_app
        flutter analyze

  build-android:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: action/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk