name: Flutter CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo_list_app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Disable Flutter analytics
      run: flutter config --no-analytics

    - name: Run all Flutter commands in project directory
      run: |
        echo "Current directory: $(pwd)"
        cd todo_list_app
        echo "Now in: $(pwd)"
        echo "Directory contents:"
        ls -la
        
        echo "Installing dependencies..."
        flutter pub get
        
        echo "Running tests..."
        flutter test
        
        echo "Checking formatting..."
        flutter format --set-exit-if-changed .
        
        echo "Analyzing code..."
        flutter analyze
        
        echo "✅ All steps completed successfully!"

  build-android:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: action/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk